### ISSUE TITLE
lag when start

### ISSUE THREAD

**Issue by AhmadNemati** [xiongwei-git/AndroidVideoPlayer#1]
I have a problem sometimes when i start for show player i have lag what should i do? 
 and another problem is start time from 30:00

thanks for your great project

**Comment by xiongwei-git** [comment]
1. When playing  with lag may be related to network conditions. I have fix some bugs,you can try again.
2. I have provided a method called  "loadMultipleVideo(ArrayList<Video> allVideo, int selectVideo, int selectFormat, int seekTime)", you can try.

According to the needs of the company project,I write this repository, not universal one。 You need to  modify it to adapt to your needs.
