### ISSUE TITLE
listview里的视频在滑动时可以悬浮小窗播放吗

### ISSUE THREAD

**Issue by K-9999** [xiongwei-git/AndroidVideoPlayer#13]
当listview滑动时可以让当前播放的视频小窗口悬浮播放吗

**Comment by xiongwei-git** [comment]
demo里面并没有演示如何在listview里面使用播放器。建议是，不要把videoplayer放到listview里面，而是浮在上面，如果item滚出屏幕，就让videoplayer缩放到角落。
