### ISSUE TITLE
Youtube links integration

### ISSUE THREAD

**Issue by sohayb** [xiongwei-git/AndroidVideoPlayer#2]
Can you add the ability to play youtube videos? That would be awesome :+1:

**Comment by xiongwei-git** [comment]
Youtube videos contain web,flv and mp4 format. Android native VideoView only support mp4 and 3gp format.  So it can't play all youtube videos. 
If use YouTube Android Player API to play youtube videos, I need to register my application to get one API key.
You can check https://developers.google.com/youtube/android/player/
