### ISSUE TITLE
要是能自动横竖屏，并且可以用ffmpeg 播放其他格式的视频就好了

### ISSUE THREAD

**Issue by tianshaokai** [xiongwei-git/AndroidVideoPlayer#4]

**Comment by flyou** [comment]
自动横竖屏需要你自行在相应地 activity中配置
  android:screenOrientation="sensor"
根据重力感应自动横竖屏

**Comment by zhy1905** [comment]
@xiongwei-git 在小米1上播放不了。一直加载中，并且黑屏，Android系统4.1.2
