### ISSUE TITLE
Return from home or other activity , player will become black screen

### ISSUE THREAD

**Issue by E-KAY** [xiongwei-git/AndroidVideoPlayer#8]
Return from Home or other activity , player will become black screen

**Comment by yuzhongxingke** [comment]
请问这个有人解决方法吗？

**Comment by xiongwei-git** [comment]
`@Override  
    public void onPause() {  
        houseDetailViewBuilder.closeVideo();  
        super.onPause();  
    }`

if u get a better way,please let me know, thankyou
